### ISSUE TITLE
能否留下联系方式？

### ISSUE THREAD

**Issue by jannson** [dsafa22/AirplayServer#1]
感谢作者这个牛逼的项目，想跟作者交流一些产品上的想法与观点，希望作者能给机会。

**Comment by dsafa22** [comment]
本项目只提供基础能力，不准备单独开发app产品。当然，如果你可以应用在你的产品上，希望可以继续打磨组件，谢谢！

**Comment by jannson** [comment]
好的，感谢回复！目前还没有直接跟此相关的产品，只是我的其它产品能跟本项目有一定的契合。
总之非常看好此项目的前景，有空我会积极参与的，为此项目的未来作一点点贡献～
