### ISSUE TITLE
投屏中断

### ISSUE THREAD

**Issue by 561546441** [dsafa22/AirplayServer#18]
你好，我在使用的过程中发现，有时候投屏会突然中断。
目前调试的结果是发现程序卡在recv的死循环里面了。程序似乎没有对recv的返回值做异常处理。

raop_rtp_mirror.c文件

`unsigned char* payload_in = malloc(payloadsize);
 unsigned char* payload = malloc(payloadsize);
 readstart = 0;
 do {
       /* payload数据 */
       ret = recv(stream_fd, payload_in + readstart, payloadsize - readstart, 0);
       readstart = readstart + ret;
} while (readstart < payloadsize);`

**Comment by 561546441** [comment]
log:
读取剩下的124字节
payloadtype 0
读取时间
读取加密数据
Receiving on socket 28
Handling request POST with URL /feedback
raop_handler_feedback
**recv ret: -1**
recv error: 104
readstart = 1060
开始解密数据

**Comment by dsafa22** [comment]
感谢反馈，这里我补充下异常逻辑

**Comment by dsafa22** [comment]
已经修复 commit:5ba1b69
