### ISSUE TITLE
你好，保存的aac文件无法播放问题，怎么解决啊？

### ISSUE THREAD

**Issue by lyeday** [dsafa22/AirplayServer#19]

**Comment by dsafa22** [comment]
dump处理的aac是不带头的，建议直接播放dump的pcm简单点
ffplay -f s16le -ac 2 -ar 44100 out.pcm

**Comment by lyeday** [comment]
我看到了有pcm格式的音频，但是我想转换成aac格式的，我加了adts头，然而还是不能播放的，有什么办法处理吗？

**Comment by dsafa22** [comment]
因为不清楚你是怎么加的，有几点可以自行检查下，1、是否每帧AAC数据都有加？2、adts头的格式（profile,channel等）是否正确？3、长度是否正确？

**Comment by lyeday** [comment]
我是每一帧都加了adts头的，adts头信息代码如下:

`
    unsigned char *adts = malloc(sizeof(unsigned char)*7);
    memset(adts, 0, 7);
    int profile = 0x27; // AAC ELC
    int freqIdx = 0x4; // 44.1KHz
    int chanCfg = 0x2; // CPE
    int packetLen = payloadsize+7;
    // fill in ADTS data
    adts[0] = 0xFF;
    adts[1] = 0xF8;
    adts[2] = (((profile - 1) << 6) + (freqIdx << 2) + (chanCfg >> 2));
    adts[3] = (((chanCfg & 3) << 6) + (packetLen >> 11));
    adts[4] = ((packetLen & 0x7FF) >> 3);
    adts[5] = (((packetLen & 7) << 5) + 0x1F);
    adts[6] = 0xFC;
`

**Comment by dsafa22** [comment]
看起来没问题，用什么播放的呢？

**Comment by lyeday** [comment]
好的，需要中间再加一次转码。
