### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by FD-** [dsafa22/AirplayServer#3]
I could not find any license information for the source code you've written (Mainly the C code  starting with `Created by Administrator on`). Please add a `LICENSE` file, some description in your `Readme.md` or a suitable header comment for the files you authored. 

I was able to find license information for much of the remaining code at https://github.com/juhovh/shairplay/blob/master/LICENSE

**Comment by FD-** [comment]
The reason I'm asking is because I'm planning to publish an open-source port of this project for the Raspberry Pi, but if your code has no license, I'm not legally allowed to do that.

**Comment by dsafa22** [comment]
Thank you. I'll update the license in these days.

**Comment by FD-** [comment]
Any news on this matter?

**Comment by dsafa22** [comment]
@FD- Fixed.

**Comment by FD-** [comment]
@dsafa22 Does that mean the code in the `src/main/cpp/lib/` folder that you authored is licensed under the LGPL?

**Comment by FD-** [comment]
Never mind, I just found you also added License headers to the individual files. Fantastic news! Will release my Raspberry Pi port soon.

**Comment by dsafa22** [comment]
@FD- Because the original license is LGPLv2.1+ .
I have no way.
