### ISSUE TITLE
Connection loss

### ISSUE THREAD

**Issue by FD-** [dsafa22/AirplayServer#5]
It seems the connection forcefully stops sometimes. From the logs, I could see that the iOS device was sending a TEARDOWN message, which lead to the server stopping the two RTP sessions (audio and video).
At first, it seemed to occur completely randomly, but after a few experiments, I found the event is somehow linked to starting and stopping Music playback on the iOS device.

Next, I had a look at captured traffic from a real AppleTV and found that sometimes, the AppleTV receives a TEARDOWN message from the iOS device, but the video stream still continues.

With these hints, I examined AirPlayServer's raop.c code and found that the TEARDOWN is handled differently (not like on the AppleTV): When a TEARDOWN message is received, we stop both audio and video RTP sessions. Instead, it seems the first TEARDOWN should only stop the audio session. When audio playback on the iOS device is started again, a new SETUP message will then be sent again that has to be handled properly. That's why some changes to the setup handler will be required, to deal with setting up a new audio session.

BTW, please [decide on a license for your code](https://github.com/dsafa22/AirplayServer/issues/3). I'd suggest the GNU GPL license to make sure all derivative works will be open source as well.

**Comment by FD-** [comment]
It's actually easier to fix than I thought, because we can just stop the audio rtp session instead of destroying it.

**Comment by dsafa22** [comment]
The correct teardown should be two, one for audio and one for video, corresponding to type 96 and 110, respectively. For convenience, only one is processed, and the audio and video are finished at the same time.

**Comment by dsafa22** [comment]
The reason for this is that the end of the audio video is also over. I didn't encounter the situation you said, so I simply handled it.

**Comment by dsafa22** [comment]
TEARDOWN-1
<plist version="1.0">
<dict>
    <key>streams</key>
    <array>
        <dict>
            <key>type</key>
            <integer>96</integer>
        </dict>
    </array>
</dict>
</plist>


TEARDOWN-2
<plist version="1.0">
<dict>
    <key>streams</key>
    <array>
        <dict>
            <key>type</key>
            <integer>110</integer>
        </dict>
    </array>
</dict>
</plist>

**Comment by dsafa22** [comment]
已修复，TEARDOWN分为音频和镜像两个部分，音频结束不会导致镜像结束了。
