### ISSUE TITLE
镜像的时候画面和声音均有延迟

### ISSUE THREAD

**Issue by xiaolouxinyue** [dsafa22/AirplayServer#9]
镜像模式下，抖音视频画面延迟0.5秒左右，声音延迟1~2秒左右。打王者荣耀的时候延迟更大。家庭网环境，网速应该不是主要问题。

**Comment by dsafa22** [comment]
感谢反馈，音画同步和延迟问题会很快解决

**Comment by hill121212** [comment]
大神，视频和音频不同步的问题，有怎么样的思路解决？我看您的项目里，有视频和音频帧的 PTS，这个是怎么样处理，能够控制视频帧和音频的同步吗？

**Comment by dsafa22** [comment]
目前加入了简单的音画同步，可以pull试用下看看。
